from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLabel, QFormLayout, QLineEdit, QPushButton, QFileDialog

def create_profile_page(main_window):
    page=QWidget()
    layout=QVBoxLayout(page)
    label=QLabel(main_window._("Profile Page - Customize your details"))
    layout.addWidget(label)
    form_layout=QFormLayout()
    main_window.profile_name_line_edit=QLineEdit()
    main_window.profile_name_line_edit.setText(main_window.user_profile.data["name"])
    form_layout.addRow(main_window._("Name:"),main_window.profile_name_line_edit)
    main_window.profile_pic_label=QLabel(main_window.user_profile.data["profile_picture"] if main_window.user_profile.data["profile_picture"] else main_window._("No file selected."))
    main_window.change_pic_button=QPushButton(main_window._("Change Picture"))
    main_window.remove_pic_button=QPushButton(main_window._("Remove Picture"))
    main_window.remove_pic_button.setVisible(bool(main_window.user_profile.data["profile_picture"]))
    main_window.change_pic_button.clicked.connect(lambda:main_window.select_profile_picture(main_window.change_pic_button,main_window.profile_pic_label,main_window.remove_pic_button))
    main_window.remove_pic_button.clicked.connect(lambda:main_window.remove_profile_picture(main_window.change_pic_button,main_window.profile_pic_label,main_window.remove_pic_button))
    form_layout.addRow(main_window._("Picture:"),main_window.change_pic_button)
    form_layout.addRow(main_window.profile_pic_label)
    form_layout.addRow(main_window.remove_pic_button)
    main_window.instagram_line_edit=QLineEdit()
    main_window.instagram_line_edit.setText(main_window.user_profile.data["social_media_links"].get("instagram",""))
    main_window.twitter_line_edit=QLineEdit()
    main_window.twitter_line_edit.setText(main_window.user_profile.data["social_media_links"].get("twitter",""))
    main_window.youtube_line_edit=QLineEdit()
    main_window.youtube_line_edit.setText(main_window.user_profile.data["social_media_links"].get("youtube",""))
    form_layout.addRow(main_window._("Instagram:"),main_window.instagram_line_edit)
    form_layout.addRow(main_window._("Twitter:"),main_window.twitter_line_edit)
    form_layout.addRow(main_window._("YouTube:"),main_window.youtube_line_edit)
    layout.addLayout(form_layout)
    save_profile_button=QPushButton(main_window._("Save Profile"))
    save_profile_button.clicked.connect(main_window.save_profile_settings)
    layout.addWidget(save_profile_button)
    layout.addStretch()
    return page
