from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLabel, QGroupBox, QHBoxLayout, QFormLayout
from PyQt5.QtWidgets import QComboBox, QLineEdit, QPushButton, QFileDialog

def create_settings_page(main_window):
    page=QWidget()
    layout=QVBoxLayout(page)
    label=QLabel(main_window._("Settings"))
    layout.addWidget(label)
    concurrent_group=QGroupBox(main_window._("Max Concurrent Downloads"))
    concurrent_layout=QHBoxLayout(concurrent_group)
    main_window.concurrent_combo=QComboBox()
    main_window.concurrent_combo.addItems(["1","2","3","4","5","10"])
    main_window.concurrent_combo.setCurrentText(str(main_window.max_concurrent_downloads))
    main_window.concurrent_combo.currentIndexChanged.connect(main_window.set_max_concurrent_downloads)
    concurrent_layout.addWidget(LabelWrapper(main_window._("Concurrent:")))
    concurrent_layout.addWidget(main_window.concurrent_combo)
    layout.addWidget(concurrent_group)
    tech_group=QGroupBox(main_window._("Technical / Appearance"))
    tech_layout=QFormLayout(tech_group)
    main_window.proxy_line_edit=QLineEdit()
    main_window.proxy_line_edit.setText(main_window.user_profile.get_proxy())
    main_window.proxy_line_edit.setPlaceholderText(main_window._("Proxy or bandwidth limit..."))
    main_window.theme_combo=QComboBox()
    main_window.theme_combo.addItems(["Dark","Light"])
    main_window.theme_combo.setCurrentText(main_window.user_profile.get_theme())
    tech_layout.addRow(main_window._("Proxy/BW:"),main_window.proxy_line_edit)
    tech_layout.addRow(main_window._("Theme:"),main_window.theme_combo)
    apply_theme_button=QPushButton(main_window._("Apply Theme"))
    apply_theme_button.clicked.connect(main_window.apply_theme_settings)
    tech_layout.addWidget(apply_theme_button)
    layout.addWidget(tech_group)
    resolution_group=QGroupBox(main_window._("Default Resolution"))
    resolution_layout=QHBoxLayout(resolution_group)
    main_window.resolution_combo=QComboBox()
    main_window.resolution_combo.addItems(["144p","240p","360p","480p","720p","1080p","1440p","2160p","4320p"])
    main_window.resolution_combo.setCurrentText(main_window.user_profile.get_default_resolution())
    resolution_layout.addWidget(LabelWrapper(main_window._("Resolution:")))
    resolution_layout.addWidget(main_window.resolution_combo)
    apply_resolution_button=QPushButton(main_window._("Apply"))
    apply_resolution_button.clicked.connect(main_window.apply_resolution_settings)
    resolution_layout.addWidget(apply_resolution_button)
    layout.addWidget(resolution_group)
    path_group=QGroupBox(main_window._("Download Path"))
    path_layout=QHBoxLayout(path_group)
    main_window.download_path_line_edit=QLineEdit()
    main_window.download_path_line_edit.setReadOnly(True)
    main_window.download_path_line_edit.setText(main_window.user_profile.get_download_path())
    browse_button=QPushButton(main_window._("Browse"))
    browse_button.clicked.connect(main_window.select_download_path)
    path_layout.addWidget(LabelWrapper(main_window._("Folder:")))
    path_layout.addWidget(main_window.download_path_line_edit)
    path_layout.addWidget(browse_button)
    layout.addWidget(path_group)
    speed_group=QGroupBox(main_window._("Download Speed Limit"))
    speed_layout=QHBoxLayout(speed_group)
    main_window.rate_limit_line_edit=QLineEdit()
    main_window.rate_limit_line_edit.setPlaceholderText(main_window._("e.g., 500K, 2M"))
    if main_window.user_profile.get_rate_limit():
        main_window.rate_limit_line_edit.setText(main_window.user_profile.get_rate_limit())
    apply_rate_button=QPushButton(main_window._("Apply"))
    apply_rate_button.clicked.connect(main_window.apply_rate_limit_settings)
    speed_layout.addWidget(LabelWrapper(main_window._("Max Rate:")))
    speed_layout.addWidget(main_window.rate_limit_line_edit)
    speed_layout.addWidget(apply_rate_button)
    layout.addWidget(speed_group)
    language_group=QGroupBox(main_window._("Language"))
    language_layout=QHBoxLayout(language_group)
    main_window.language_combo=QComboBox()
    main_window.language_combo.addItems(["English","Türkçe"])
    current_lang="Türkçe" if main_window.user_profile.get_language()=="tr" else "English"
    main_window.language_combo.setCurrentText(current_lang)
    apply_language_button=QPushButton(main_window._("Apply Language"))
    apply_language_button.clicked.connect(main_window.apply_language_settings)
    language_layout.addWidget(LabelWrapper(main_window._("Language:")))
    language_layout.addWidget(main_window.language_combo)
    language_layout.addWidget(apply_language_button)
    layout.addWidget(language_group)
    layout.addStretch()
    return page

class LabelWrapper(QLabel):
    def __init__(self,text):
        super().__init__(text)
